[feat] ftrace 시각화 완료(refactor 필요)
n-perf/front pull request #9
Opened 2022-05-03 08:27 UTC by TaeseoungKim

[feat] ftrace 시각화 완료(refactor 필요)

2022-05-03 11:04 UTC, ClaudiaJKang requested changes
수고하셨습니다! 코드 리뷰 해보았는데 수정해보시고 궁금한 점 있으시면 알려주세요!

그리고 커밋 단위는 비슷한 내용을 수정한 사항들이 많아서 내일 수업 시간 끝나고 rebase 작업을 같이 진행해보아야 할 것 같습니다.

마지막으로 PR 제목에서 `(refactor 필요)`는 삭제부탁드립니다.

2022-05-03 11:04 UTC, claudiajkang commented on net-perf/src/components/loadFile/LoadFile.js
> +		}
```suggestion
               let index = parseInt(e.target.id);
               setFilenames(prevState => ({
					...prevState,
					index : e.target.files[index].name,
				}));
```

`e.target.id`을 index 변수로 선언하게 되면 switch 문 없이 이렇게 줄일 수 있을 것 같습니다.

2022-05-03 11:04 UTC, ClaudiaJKang commented on net-perf/src/components/output/MyResponsiveLine.js
> +		/>
이 부분은 따로 나중에 사용되는 코드인가요??

2022-05-03 11:04 UTC, ClaudiaJKang commented on net-perf/src/data/iperf3.json
>  {
.gitignore에 data 폴더를 추가해서 해당 파일이 수정되도 git에 등록되지 않도록 수정이 필요해보입니다.

2022-05-03 11:04 UTC, ClaudiaJKang commented on net-perf/src/styles/sass/main.css.map
> +{"version":3,"sourceRoot":"","sources":["common/LoadFile.scss","common/color.scss","common/Output.scss","main.scss"],"names":[],"mappings":";AAEA;EACC;EACA;;;AAID;EACC;EACA;EACA,kBCTM;EDWN;EAEA;EACA;
이 파일도 gitignore에 추가되어야 될 것 같네요!

2022-05-04 05:02 UTC, TaeseoungKim commented on net-perf/src/components/output/MyResponsiveLine.js
> +		/>
사용이 안될것같아 주석처리하였지만 혹시 몰라서 안지웠습니다!

2022-05-04 05:03 UTC, TaeseoungKim commented on net-perf/src/data/iperf3.json
>  {
감사합니다 ㅎㅎ

2022-05-10 13:50 UTC, ClaudiaJKang commented
@TaeseoungKim 이 PR 은 #12로 머지 된거죠?

2022-05-18 05:57 UTC, closed without merging